# Белый список: окна времени, в которые разрешено проведение работ в каждой из зон доступности.
white_list:
  Zone_1: #zoneId
    - start_hour: "00:30"
      end_hour: "05:00"
  Zone_2: #zoneId
    - start_hour: "23:00"
      end_hour: "06:00"
  Zone_3: #zoneId
    - start_hour: "02:00"
      end_hour: "04:00"
  Zone_4: #zoneId
    - start_hour: "23:00"
      end_hour: "06:00"

# Черный список: зоны доступности, в которых проведения любых работ кроме критичных полностью запрещено (имеет приоритет над белым списком).
black_list: []
# Количество зон доступности, для которых в любой момент времени гарантировано, что в них не проводится никаких работ 
# (зоны доступности из черного списка никогда не удовлетворяют этому условию).
min_avialable_zones: 1
# * Паузы (мин) для каждой из зон доступности между работами, которые в ней будут проводиться.
pauses: 
  Zone_1: 30
  Zone_2: 30
  Zone_3: 30
  Zone_4: 30
# Минимальная длительность работ: 5 минут для автоматических и 30 минут для ручных. 
min_work_duration_minutes:
  automatic: 5
  manual: 30
# Максимальная длительность работ - 6 часов, для обычных работ любого типа и без ограничений для критических. 
max_work_duration_minutes: # only for regular, not for critical works
  automatic: 360
  manual: 360
# Дедлайн не может превышать текущую дату более, чем на 4 недели. Желаемое время начала ручных работ кратно 5 минутам, автоматических - 1 минуте. 
max_deadline_days: 28
