// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.5-0.20230403173426-fd06f5aed350 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
)

// Defines values for WorkPriority.
const (
	Critical WorkPriority = "critical"
	Regular  WorkPriority = "regular"
)

// Defines values for WorkStatus.
const (
	WorkStatusCancelled  WorkStatus = "cancelled"
	WorkStatusInProgress WorkStatus = "in_progress"
	WorkStatusPlanned    WorkStatus = "planned"
)

// Defines values for WorkWorkType.
const (
	Automatic WorkWorkType = "automatic"
	Manual    WorkWorkType = "manual"
)

// Defines values for GetSheduleParamsStatuses.
const (
	GetSheduleParamsStatusesCancelled  GetSheduleParamsStatuses = "cancelled"
	GetSheduleParamsStatusesInProgress GetSheduleParamsStatuses = "in_progress"
	GetSheduleParamsStatusesPlanned    GetSheduleParamsStatuses = "planned"
)

// Error defines model for error.
type Error struct {
	Alternative *[]interface{} `json:"alternative,omitempty"`
	ErrorCode   *uint32        `json:"errorCode,omitempty"`
	Message     *string        `json:"message,omitempty"`
}

// MoveWork defines model for moveWork.
type MoveWork struct {
	DurationMinutes *int32    `json:"durationMinutes,omitempty"`
	StartDate       time.Time `json:"startDate"`
}

// PostWork defines model for postWork.
type PostWork struct {
	Deadline        *time.Time `json:"deadline,omitempty"`
	DurationMinutes *int32     `json:"durationMinutes,omitempty"`
	StartDate       *time.Time `json:"startDate,omitempty"`
	Zone            *string    `json:"zone,omitempty"`
}

// ProlongateWork defines model for prolongateWork.
type ProlongateWork struct {
	DurationMinutes *int32 `json:"durationMinutes,omitempty"`
}

// Work defines model for work.
type Work struct {
	Deadline        *time.Time    `json:"deadline,omitempty"`
	DurationMinutes *int32        `json:"durationMinutes,omitempty"`
	Id              *string       `json:"id,omitempty"`
	Priority        *WorkPriority `json:"priority,omitempty"`
	StartDate       *time.Time    `json:"startDate,omitempty"`
	Status          *WorkStatus   `json:"status,omitempty"`
	WorkType        *WorkWorkType `json:"workType,omitempty"`
	Zone            *string       `json:"zone,omitempty"`
}

// WorkPriority defines model for Work.Priority.
type WorkPriority string

// WorkStatus defines model for Work.Status.
type WorkStatus string

// WorkWorkType defines model for Work.WorkType.
type WorkWorkType string

// GetSheduleParams defines parameters for GetShedule.
type GetSheduleParams struct {
	// FromDate Starts from
	FromDate *time.Time `form:"fromDate,omitempty" json:"fromDate,omitempty"`

	// ToDate Starts to
	ToDate *time.Time `form:"toDate,omitempty" json:"toDate,omitempty"`

	// Zones List of zones
	Zones *[]string `form:"zones,omitempty" json:"zones,omitempty"`

	// Statuses Statuses of work to get
	Statuses *[]GetSheduleParamsStatuses `form:"statuses,omitempty" json:"statuses,omitempty"`
}

// GetSheduleParamsStatuses defines parameters for GetShedule.
type GetSheduleParamsStatuses string

// AddWorkJSONRequestBody defines body for AddWork for application/json ContentType.
type AddWorkJSONRequestBody = PostWork

// MoveWorkByIdJSONRequestBody defines body for MoveWorkById for application/json ContentType.
type MoveWorkByIdJSONRequestBody = MoveWork

// ProlongateWorkByIdJSONRequestBody defines body for ProlongateWorkById for application/json ContentType.
type ProlongateWorkByIdJSONRequestBody = ProlongateWork

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get shedule with works
	// (GET /shedule)
	GetShedule(w http.ResponseWriter, r *http.Request, params GetSheduleParams)
	// Create new planned work in avialable zone
	// (POST /work)
	AddWork(w http.ResponseWriter, r *http.Request)
	// Get planned work by id
	// (GET /work/{workId})
	GetWorkById(w http.ResponseWriter, r *http.Request, workId string)
	// Cancel planned work by id
	// (PUT /work/{workId}/cancel)
	CancelWorkById(w http.ResponseWriter, r *http.Request, workId string)
	// Move start time and duration for planned work
	// (PUT /work/{workId}/move)
	MoveWorkById(w http.ResponseWriter, r *http.Request, workId string)
	// Prolongate work duration started work
	// (PUT /work/{workId}/prolongate)
	ProlongateWorkById(w http.ResponseWriter, r *http.Request, workId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetShedule operation middleware
func (siw *ServerInterfaceWrapper) GetShedule(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSheduleParams

	// ------------- Optional query parameter "fromDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "fromDate", r.URL.Query(), &params.FromDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fromDate", Err: err})
		return
	}

	// ------------- Optional query parameter "toDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "toDate", r.URL.Query(), &params.ToDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toDate", Err: err})
		return
	}

	// ------------- Optional query parameter "zones" -------------

	err = runtime.BindQueryParameter("form", true, false, "zones", r.URL.Query(), &params.Zones)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "zones", Err: err})
		return
	}

	// ------------- Optional query parameter "statuses" -------------

	err = runtime.BindQueryParameter("form", true, false, "statuses", r.URL.Query(), &params.Statuses)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "statuses", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShedule(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AddWork operation middleware
func (siw *ServerInterfaceWrapper) AddWork(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddWork(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetWorkById operation middleware
func (siw *ServerInterfaceWrapper) GetWorkById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameter("simple", false, "workId", mux.Vars(r)["workId"], &workId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkById(w, r, workId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CancelWorkById operation middleware
func (siw *ServerInterfaceWrapper) CancelWorkById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameter("simple", false, "workId", mux.Vars(r)["workId"], &workId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelWorkById(w, r, workId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// MoveWorkById operation middleware
func (siw *ServerInterfaceWrapper) MoveWorkById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameter("simple", false, "workId", mux.Vars(r)["workId"], &workId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveWorkById(w, r, workId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ProlongateWorkById operation middleware
func (siw *ServerInterfaceWrapper) ProlongateWorkById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameter("simple", false, "workId", mux.Vars(r)["workId"], &workId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProlongateWorkById(w, r, workId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/shedule", wrapper.GetShedule).Methods("GET")

	r.HandleFunc(options.BaseURL+"/work", wrapper.AddWork).Methods("POST")

	r.HandleFunc(options.BaseURL+"/work/{workId}", wrapper.GetWorkById).Methods("GET")

	r.HandleFunc(options.BaseURL+"/work/{workId}/cancel", wrapper.CancelWorkById).Methods("PUT")

	r.HandleFunc(options.BaseURL+"/work/{workId}/move", wrapper.MoveWorkById).Methods("PUT")

	r.HandleFunc(options.BaseURL+"/work/{workId}/prolongate", wrapper.ProlongateWorkById).Methods("PUT")

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY32/bNhD+V4jbgL2okp12L3pr02Iw0AzFHGAPRTBcxLPNhiJV8mTXC/y/DyT9K7ac",
	"OG3apENeEls+3n28++47itdQ2bqxhgx7KK/BVxOqMX4k56wLHxpnG3KsKD5GzeQMsppS+KqY6vhctg5Z",
	"WXOmTMvJlL5g3WiC8iSDkXU1MpSgDL88gQx43lD6SmNysMjAMzp+ixz9ru0lMr1gVdNmjWenzBgWi/UT",
	"dA7nwUcEfWrlTR/t4aA1eY/jaH7Qu738RBVHazulv6272k/L42zf0edWOZJQftxaf9GBvLGeDyAnlFqZ",
	"o8Nmj7HXDP61CeI6Erwd9m/jxNbendXWjJG/U+26Ys6eTK6V7CB3SIqyTvE8ejRtHSjkaNxqdJBB5RSr",
	"CvUWlzZLv6J6npFbvx2r0WgMyRALTUVax8/K/NM4O3bkfWfokNbz+HDjqUbTooYMsGVbI6uqc+lXEyg8",
	"UmZkUwF95VQTKgIlnE+UF57clJyQNCVtG5JiZJ0Y/vVOsMPqSigjBue/eXGuzJUdjcTQ6jYsF6dtk0MG",
	"WlVkfERmsA5xXzdYTUic5D3IoHUaSpgwN2VRzGazHOOvuXXjYrnUF+8Hp+/+HL57cZL38gnXOmyXFcdN",
	"BsoLPyHZak2htFNyPsHv57283w/GtiGDjYISXua9/CVk0CBPYr2KtDYCHBPvJ+EP4qV/EjPFExFq5CE6",
	"TdwdyGQ2XHoK3h3WxOQ8lB93HQ4DvbwYOVtDBvSl0VHP2bUUCgElfG7JzSFbJSxYRjomQcQoiMk8zbPj",
	"FfUAFrbHIWH7nXC8V56FHYlAYn8clpXpJvR6Vu/1xs0x2pkGbj35ACGUV7AVgQxHAfHLxd1Yvk0PdoBf",
	"hMz7xoauCM5Per3wr7KGyUTuYtNoVUVaFp982Nz1FqpfHY2ghF+KzamoWB6JiqjoUQx2ctNWFflRq2Pb",
	"veq92m+R2IOxN5QUxoqRbY0M1r8/IL50XusAODDxxKZXSrUyzMC3dY1uflsTM459PF0se/cirCvW0836",
	"DkU4dYRMwtBMLKuaSKOMwKlCjZeaIpP3ROK1lHFEpwYiz2+snD9YhtZnoI4k3Qfz5tQVSL/Y41x/PyUb",
	"kogqRpKJLD+g/G9QimU2nxTl7pPxFQsj7zYULK7D34Fc3Dqcbni/nAslu4ZTIMab+UDeNZ0GciWCsJS7",
	"MCo3apcQ7bFkW/t21f5Ztb5BtTqrexdfijRjooS1XQoWfz6GOcnySZHnDvmJgB9Pf35Sqt3GiDvZVtt0",
	"WdLJtTM7JRFfqUQ4DQo0Uqze+uK7xHbMPf6dLW8kHpN9Dz+p1/csHdW6V75ysfMCLZQXNrpCnR8xy3+8",
	"Ej+35JEted/GubNNN/dEB5v1w9okScA6XsRxqEk/3LiA+n+16s7lWkctj83Zcyv+tK14bIl3WzA4iV5T",
	"D6TLrgIbVUz7sLhY/BcAAP///yUz+J8YAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
