// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
)

// Defines values for PostWorkPriority.
const (
	PostWorkPriorityCritical PostWorkPriority = "critical"
	PostWorkPriorityRegular  PostWorkPriority = "regular"
)

// Defines values for PostWorkWorkType.
const (
	PostWorkWorkTypeAutomatic PostWorkWorkType = "automatic"
	PostWorkWorkTypeManual    PostWorkWorkType = "manual"
)

// Defines values for WorksPriority.
const (
	WorksPriorityCritical WorksPriority = "critical"
	WorksPriorityRegular  WorksPriority = "regular"
)

// Defines values for WorksStatus.
const (
	WorksStatusCanceled   WorksStatus = "canceled"
	WorksStatusInProgress WorksStatus = "in_progress"
	WorksStatusPlanned    WorksStatus = "planned"
)

// Defines values for WorksWorkType.
const (
	WorksWorkTypeAutomatic WorksWorkType = "automatic"
	WorksWorkTypeManual    WorksWorkType = "manual"
)

// Defines values for GetscheduleParamsStatuses.
const (
	GetscheduleParamsStatusesCanceled   GetscheduleParamsStatuses = "canceled"
	GetscheduleParamsStatusesInProgress GetscheduleParamsStatuses = "in_progress"
	GetscheduleParamsStatusesPlanned    GetscheduleParamsStatuses = "planned"
)

// Error defines model for error.
type Error struct {
	Alternative *[]struct {
		Deadline        *time.Time `json:"deadline,omitempty"`
		DurationMinutes *int32     `json:"durationMinutes,omitempty"`
		StartDate       *time.Time `json:"startDate,omitempty"`
		Zones           *[]string  `json:"zones,omitempty"`
	} `json:"alternative,omitempty"`
	ErrorCode *string `json:"errorCode,omitempty"`
	Message   *string `json:"message,omitempty"`
}

// PostWork defines model for postWork.
type PostWork struct {
	Deadline        *time.Time        `json:"deadline,omitempty"`
	DurationMinutes *int32            `json:"durationMinutes,omitempty"`
	Priority        *PostWorkPriority `json:"priority,omitempty"`
	StartDate       *time.Time        `json:"startDate,omitempty"`
	WorkType        *PostWorkWorkType `json:"workType,omitempty"`
	Zones           *interface{}      `json:"zones,omitempty"`
}

// PostWorkPriority defines model for PostWork.Priority.
type PostWorkPriority string

// PostWorkWorkType defines model for PostWork.WorkType.
type PostWorkWorkType string

// ProlongateWork defines model for prolongateWork.
type ProlongateWork struct {
	DurationMinutes *int32 `json:"durationMinutes,omitempty"`
}

// Works defines model for works.
type Works = []struct {
	Deadline        *time.Time     `json:"deadline,omitempty"`
	DurationMinutes *int32         `json:"durationMinutes,omitempty"`
	Id              *string        `json:"id,omitempty"`
	Priority        *WorksPriority `json:"priority,omitempty"`
	StartDate       *time.Time     `json:"startDate,omitempty"`
	Status          *WorksStatus   `json:"status,omitempty"`
	WorkId          *string        `json:"workId,omitempty"`
	WorkType        *WorksWorkType `json:"workType,omitempty"`
	Zones           *[]string      `json:"zones,omitempty"`
}

// WorksPriority defines model for Works.Priority.
type WorksPriority string

// WorksStatus defines model for Works.Status.
type WorksStatus string

// WorksWorkType defines model for Works.WorkType.
type WorksWorkType string

// GetscheduleParams defines parameters for Getschedule.
type GetscheduleParams struct {
	// FromDate Starts from
	FromDate *time.Time `form:"fromDate,omitempty" json:"fromDate,omitempty"`

	// ToDate Starts to
	ToDate *time.Time `form:"toDate,omitempty" json:"toDate,omitempty"`

	// Zones List of zones
	Zones *[]string `form:"zones,omitempty" json:"zones,omitempty"`

	// Statuses Statuses of work to get
	Statuses *[]GetscheduleParamsStatuses `form:"statuses,omitempty" json:"statuses,omitempty"`
}

// GetscheduleParamsStatuses defines parameters for Getschedule.
type GetscheduleParamsStatuses string

// AddWorkJSONRequestBody defines body for AddWork for application/json ContentType.
type AddWorkJSONRequestBody = PostWork

// MoveWorkByIdJSONRequestBody defines body for MoveWorkById for application/json ContentType.
type MoveWorkByIdJSONRequestBody = Works

// ProlongateWorkByIdJSONRequestBody defines body for ProlongateWorkById for application/json ContentType.
type ProlongateWorkByIdJSONRequestBody = ProlongateWork

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get schedule with works
	// (GET /schedule)
	Getschedule(w http.ResponseWriter, r *http.Request, params GetscheduleParams)
	// Create new planned work in avialable zone
	// (POST /work)
	AddWork(w http.ResponseWriter, r *http.Request)
	// Get planned work by id
	// (GET /work/{workId})
	GetWorkById(w http.ResponseWriter, r *http.Request, workId string)
	// Cancel planned work by id
	// (PUT /work/{workId}/cancel)
	CancelWorkById(w http.ResponseWriter, r *http.Request, workId string)
	// Move start time and duration for planned work
	// (PUT /work/{workId}/move)
	MoveWorkById(w http.ResponseWriter, r *http.Request, workId string)
	// Prolongate work duration started work
	// (PUT /work/{workId}/prolongate)
	ProlongateWorkById(w http.ResponseWriter, r *http.Request, workId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// Getschedule operation middleware
func (siw *ServerInterfaceWrapper) Getschedule(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetscheduleParams

	// ------------- Optional query parameter "fromDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "fromDate", r.URL.Query(), &params.FromDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fromDate", Err: err})
		return
	}

	// ------------- Optional query parameter "toDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "toDate", r.URL.Query(), &params.ToDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toDate", Err: err})
		return
	}

	// ------------- Optional query parameter "zones" -------------

	err = runtime.BindQueryParameter("form", true, false, "zones", r.URL.Query(), &params.Zones)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "zones", Err: err})
		return
	}

	// ------------- Optional query parameter "statuses" -------------

	err = runtime.BindQueryParameter("form", true, false, "statuses", r.URL.Query(), &params.Statuses)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "statuses", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Getschedule(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AddWork operation middleware
func (siw *ServerInterfaceWrapper) AddWork(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddWork(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetWorkById operation middleware
func (siw *ServerInterfaceWrapper) GetWorkById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameter("simple", false, "workId", mux.Vars(r)["workId"], &workId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkById(w, r, workId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CancelWorkById operation middleware
func (siw *ServerInterfaceWrapper) CancelWorkById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameter("simple", false, "workId", mux.Vars(r)["workId"], &workId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelWorkById(w, r, workId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// MoveWorkById operation middleware
func (siw *ServerInterfaceWrapper) MoveWorkById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameter("simple", false, "workId", mux.Vars(r)["workId"], &workId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveWorkById(w, r, workId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ProlongateWorkById operation middleware
func (siw *ServerInterfaceWrapper) ProlongateWorkById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameter("simple", false, "workId", mux.Vars(r)["workId"], &workId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workId", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProlongateWorkById(w, r, workId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/schedule", wrapper.Getschedule).Methods("GET")

	r.HandleFunc(options.BaseURL+"/work", wrapper.AddWork).Methods("POST")

	r.HandleFunc(options.BaseURL+"/work/{workId}", wrapper.GetWorkById).Methods("GET")

	r.HandleFunc(options.BaseURL+"/work/{workId}/cancel", wrapper.CancelWorkById).Methods("PUT")

	r.HandleFunc(options.BaseURL+"/work/{workId}/move", wrapper.MoveWorkById).Methods("PUT")

	r.HandleFunc(options.BaseURL+"/work/{workId}/prolongate", wrapper.ProlongateWorkById).Methods("PUT")

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY32/bNhD+V4jbgL2osuN0L3prsmAw0A7FEmAPQTAw4tlmQ5Hs8WTXC/y/D6RsObWV",
	"xG5+rFnzZFm6453uvu/jiddQuso7i5YDFNcQyglWMl0ikaN44cl5JNaYbkvDSFaynmL8qxmrsG2lUCqj",
	"bTIZOaokQwFKMr5hXSFkwHOPUEBg0nYMiwxUTZK1sx+0rblZpHXUlg8HaydtGcdI0SuwJP5N8h6B/nG2",
	"Wb5NfctkeUMSyTks1jfc5Scsedsia4p17BR2rldhCHLc9axrbe8C/+Xo6omqil9k5Q1CMch2qbAn7Ujz",
	"PLnauoLiHAjHtZEEGZSkWZfSwEVH8G9ozszR1Vm6uY5WSVtLAxnIml0lWZed0dq+ti94Dqo8gAxUOYge",
	"Dbb36nxne8gZZ8eS8ZYmPbDkXTFjWcJT021PYGjVWcHnxUtgyXW4GcsbaS2qGEvaEk261PZvT25MGEJn",
	"5FjfYff7PAYiH09poom2I9c0PZSkfewiFHA20UEEpCmSUDhF4zwqMXIkTv88EUyyvBLaiuHZL0GcaXvl",
	"RiNx6kwd3cVx7XPIwOgSbUivamUVw77zspygGOR9yKAmAwVMmH3R681ms1ymp7mjcW/pGnrvh8cnf5ye",
	"vBnk/XzClUnvoDniCiJhRKShqg1GOEyRQpP+Qd7PDw6isfNopddQwGHezw8hAy95ksrXW/nGP2Pk7Sr8",
	"jtwGEDPNE9FQJy3bID72Odq1a8UAJCtkpADF+eaSpxGVQYzIVZABfvEmyTxTjbEXUMDnGmkO2apm0TKh",
	"OAPCz7UkVCvztQTtAu9Fdksu7HbLhN0T5fFeBxZuJBqE75TLyvQbVLirDFwHDDGF2F/BTkQ47JRIWDp3",
	"5/IgGdnI+yIWPngXeRHXHvT78ad0ltEm8ErvjS4TLHufQny36xtJ/Uw4ggJ+6q1ntN5yQOs1sE56sFGb",
	"uiwxjGqTmPe2/3abJImGiRxaCevEyNVWRetfHzHBZnzsSHBo0wBpVmK1Mswg1FUlaX4njVmOI0mhZe9F",
	"9EzlSNuiCx2qcEwoGYXFmVj2tYGNtkJOtTTy0mDC8pZOvFMq7fINhTDwkVPzR6tRO+l1lGmfnGNuuqX3",
	"4nuA3TMA6UgqsezKdwXefTq3gnPC7xrKvetmIlncudF9tfrlXGjVtc9FgB3Nh+q+fW6oVnIKS+GM++5a",
	"N5cz0ibabqro5r7xKoAPEcDO9t4HmF6zXSUtrLukMD3eBTqN5Y+OnufXsReK2LuAdS9oK9ecJnVC9oOb",
	"okjfhiLOp0JaJVafr+kD52bMLRhH7/8axI8/OdyK372KlYuNYwChg3BpKWny18HiRRNyX9rcS9L1wdet",
	"VP3YmjQC0MZLedxG0Y9fnaj9v4i6cVrY0ctda/bKxZfLxV17vMnBxeLfAAAA///TqC3uoRkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
